/* =====================================================================
   CareSync Health Network — Sample ctrl.audit_log row
   Target: Azure SQL Database
   Inserts 1 hardcoded audit record (excludes autogenerated columns:
   audit_id [identity], created_timestamp [default]).
   ===================================================================== */

INSERT INTO ctrl.audit_log
    (adf_run_id, table_id, stage, status, start_time)
VALUES
    ('123', 1, 'SOURCE_TO_SILVER', 'IN_PROGRESS', SYSUTCDATETIME());
GO
